apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ai-course
    io.kompose.service: redis-data
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
