spring:
  datasource:
    url: jdbc:postgresql://43.134.166.185:5432/scheduler
#    url: jdbc:postgresql://localhost:5432/scheduler
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Wasd2333
#    url: jdbc:h2:file:./data/scheduler;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true