spring:
  datasource:
    url: jdbc:postgresql://43.134.166.185:5432/scheduler
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Wasd2333
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      keepalive-time: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true
  security.oauth2.client:
    provider:
      azure:
        authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
        token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
        jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        user-name-attribute: name
    registration:
      azure:
        provider: azure
        client-id: f3ee6226-fd8b-4cae-a9e7-f3c211b0970b
        client-secret:
        redirect-uri: "{baseUrl}/login/oauth2/code/"
        authorization-grant-type: authorization_code
        scope:
          - openid
          - profile
          - offline_access
