spring:
  datasource:
    url: jdbc:postgresql://43.134.166.185:5432/scheduler
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Wasd2333
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true